### ISSUE TITLE
Gitadora unable to get past 5-1698-0000 error

### ISSUE THREAD

**Issue by jackiecorn** [spice2x/spice2x.github.io#140]
## Game and version
Gitadora, tried on both Matixx and Tri-Boost ReEVOLVE

## Version of spice2x
1.0-V-2024-02-02T19:10:35

## Laptop
I'm running on a mini PC (Lenovo ThinkStation Tiny P320), which has a dedicated nVidia P600 GPU. I have disabled the onboard intel GPU in device manager to make sure only the dGPU is running.

## Attached log.txt file, if available
[log.txt](https://github.com/spice2x/spice2x.github.io/files/14231581/log.txt)

## Describe the issue
After starting spice64.exe, I get an error at startup right after LED UNIT - OK. The error is 5-1698-0000. I tried multiple versions of Gitadora but still couldn't get past it. I also tried to install in multiple systems, including a Surface Book with iGPU + nVidia dGPU.
![image](https://github.com/spice2x/spice2x.github.io/assets/6892625/8416be3d-c651-4178-95ac-f063e0000c57)

**Comment by LupinThidr** [comment]
Gitadora is apparently extremely picky about files from previous games existing... if you extracted the game / updates over a previous copy, start fresh

**Comment by jackiecorn** [comment]
> I believe this is the error that shows when the files are marked as read only.
> 
> In addition to removing the read only attribute, for re:evolve, try this:
> 
> ```
> 5-1698-0000
> uncheck the Read Only attribute on contents folders 
> and remove following files from directory 
> \contents\data\product\aep_x64\
> \contents\data\product\aep\
> 
> battle_matching_3.bin
> beargarden_3.bin
> common_3.bin
> custom_3.bin
> entry_3.bin
> game_combo_3.bin
> game_common_3.bin
> game_dm_3.bin
> game_gf_3.bin
> game_session.bin
> home.bin
> mission_result.bin
> record_3.bin
> select_music_3.bin
> tab_3.bin
> title_3.bin
> warning_3.bin
> ```
> 
> I think it was just a bad dump?

Thank you so much! After changing the permissions, and deleting the files, both Matixx and re:EVOLVE worked!
I downloaded the files on a mac and transferred them over on windows, so some file permissions might have been changed unintentionally.

I'm curious why the files needed to be deleted from re:EVOLVE though, as they were origintally included in the torrent but somehow corrupts the game?

I've seen this error [come up a few times for other people](https://www.emuline.org/topic/2404-arcade-pc-gitadora-matixx-konami/?do=findComment&comment=148399). So might be helpful to add a note in an FAQ or troubleshooting guide.

Thanks again!
