### ISSUE TITLE
Marking patches as "auto-apply" in patches.json

### ISSUE THREAD

**Issue by sp2xdev** [spice2x/spice2x.github.io#153]
Anonymous user requests:

```save the configuration of patches to be auto-applied without consulting %appdata%/spicetools_patch_manager.json. Perhaps through a name in patches.json or through a separate file alongside patches.json? This would make it easier to transfer patch configurations between computers ```

**Comment by llm96** [comment]
This would be nice. Maybe a command-line argument with one or more files to load patches from? e.g.

```
-sp2x-patch-apply 120hz.json [...]
```

Admittedly, that sounds very similar to how [mempatch-hook](https://github.com/djhackersdev/bemanitools/blob/master/doc/tools/mempatch-hook.md) already works.
