### ISSUE TITLE
[NOTICE] Upcoming breaking changes - removal of KFControl, Lua scripting, VR mode, and ifs_layeredfs

### ISSUE THREAD

**Issue by sp2xdev** [spice2x/spice2x.github.io#242]
In a future release, a few breaking changes will be made to spice2x:

1. Remove KFControl
2. Remove Lua scripting
3. Remove built-in version of (old) ifs_layeredfs #125
4. Remove VR mode

### 1. KFControl

This was a mode in spicecfg (`spicecfg.exe -kfcontrol`) for redirecting sdvx cab input to other applications. People can just run an old binary, not like kfcontrol mode was benefiting from any new bug fixes or features.

Alternatively, you can use https://github.com/djhackersdev/bemanitools/blob/master/doc/vigem/vigem-sdvxio.md

### 2. Lua scripting

While this can be useful in theory, I assume no one wrote any Lua scripts, let alone know that this feature exists at all. The Lua bridge stuff takes up a lot of space and this is unnecessary baggage for most people.

### 3. built-in version of old ifs_layeredfs

This is causing more trouble than it's worth, since it's an easy trap to fall into for newcomers. Removing this will break a small number of users who rely on this to get their setup working, but everyone should just be moving to the [latest DLL hook](https://github.com/mon/ifs_layeredfs) without any loss of functionality.

### 4. DRS VR mode

VR mode is super niche & experimental feature for DRS. Contrary to what it sounds like, this was only really for tracking movement and mapping to dancefloor input. It did not replace the screen, nor the motion camera (for *down* movements). Removal of openvr library alone saves about 1MB of disk space. The one cool thing from VR feature was the dance floor LED display in the VR overlay window. The most recent beta version introduces a DRS subscreen which does the same thing.

**Comment by LupinThidr** [comment]
There was a hook dll released with bemanitools that basically did the same thing as KFControl, I forgot the name of it (maybe sdvxio-bio2?) but it's mentioned on a forum thread using the exact same "multiple top players tested and verified there was zero latency" phrase. Might be a good idea to link to that if you manage to dig it up 

For 2. what about OpenVR? I don't think it works correctly or was even finished

**Comment by LupinThidr** [comment]
found it: https://github.com/djhackersdev/bemanitools/blob/master/doc/vigem/vigem-sdvxio.md

**Comment by AllanCat** [comment]
Sorry to bump closed thread, but after this change the parameters of ifs_layeredfs stops to working on spice2x.
mainly these two:
--layered-allowlist=a,b,c,d
--layered-blocklist=a,b,c,d

In previous Spice2x version add those to command line just works.
