### ISSUE TITLE
Bind Many fails to loop around correctly

### ISSUE THREAD

**Issue by sp2xdev** [spice2x/spice2x.github.io#84]
Repro steps:

1. spicecfg
2. Check Bind Many
3. Start binding keys
4. Eventually, you reach the end
5. Expected it to stop looping, or loop to the first button. Instead, it'll jump to a seemingly random button in the list.

**Comment by scatterfish** [comment]
Simple fix, tested with keyboard and controller input.

Stopping at the end: [spice2x_bind_many_stop.txt](https://github.com/spice2x/spice2x.github.io/files/13736981/spice2x_bind_many_stop.txt)
Looping at the end: [spice2x_bind_many_loop.txt](https://github.com/spice2x/spice2x.github.io/files/13736984/spice2x_bind_many_loop.txt)

**Comment by scatterfish** [comment]
Sorry, I somehow missed that during my testing. I had tried another way of implementing the fix before, and this way seems to be unaffected by that problem. I'm less happy with how much more code it changes, but it seems to actually work.

Stopping at the end (but not broken this time hopefully: [spice2x_bind_many_stop_alternative.txt](https://github.com/spice2x/spice2x.github.io/files/13747370/spice2x_bind_many_stop_alternative.txt)

Doing some more testing, it seems that the "random" button which the Bind Many option jumps to, and the button at which the previous patches stopped, are actually off by one from each other in the list. For example, in Bishi Bashi, the previous patches stopped at `P2 Disk+`, while the original bug jumps to `P2 Disk +/- Slowdown`, which is the next button after `P2 Disk+`. When this new patch goes from `P2 Disk+` to `P2 Disk +/- Slowdown`, there's also a significant delay.

I'm unsure what implications that has.
